# Generated by Django 3.1.6 on 2021-02-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_paper',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='question_paper',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=None),
        ),
    ]
