# Generated by Django 3.1.6 on 2021-02-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210226_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='mcq_question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='mcq_Question',
        ),
        migrations.AddField(
            model_name='student_answer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.student'),
        ),
    ]
